2019-11-29 16:24:10,482 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-29 16:25:03,514 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-29 16:25:29,315 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-29 17:04:53,736 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-29 17:17:36,854 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-29 17:21:05,210 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-29 17:22:35,413 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-29 22:53:52,185 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-29 22:57:05,480 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-29 22:58:37,534 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-29 23:34:51,696 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-29 23:44:34,822 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-29 23:49:04,740 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-29 23:50:08,837 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:43]
2019-11-30 00:30:08,795 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:45]
2019-11-30 00:33:25,358 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:45]
2019-11-30 00:37:08,525 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:45]
2019-11-30 01:10:45,612 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:45]
2019-11-30 01:57:13,896 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:45]
2019-11-30 02:26:39,621 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:45]
2019-11-30 03:05:06,542 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:47]
2019-11-30 03:25:55,985 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:47]
2019-11-30 03:59:08,787 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:49]
2019-11-30 13:19:07,390 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:52]
2019-11-30 14:19:18,419 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:52]
2019-11-30 14:19:37,975 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:52]
2019-11-30 14:20:06,409 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:52]
2019-11-30 14:33:00,545 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:52]
2019-11-30 14:33:14,546 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:52]
2019-11-30 16:03:10,132 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:52]
2019-11-30 16:03:55,045 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:52]
2019-11-30 16:04:05,156 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:52]
2019-11-30 19:55:12,039 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:74]
2019-11-30 20:01:19,781 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:74]
2019-11-30 20:12:51,587 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:74]
2019-11-30 20:49:36,746 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:77]
2019-11-30 23:25:40,475 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:77]
2019-12-01 00:10:22,080 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:77]
2019-12-01 00:10:32,347 ERROR: Exception on /search [GET] [in d:\projects\microblog\myenv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "d:\projects\microblog\myenv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\projects\microblog\myenv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\projects\microblog\myenv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\projects\microblog\myenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\projects\microblog\myenv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\projects\microblog\myenv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\projects\microblog\myenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\projects\microblog\app\main\routes.py", line 141, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "D:\projects\microblog\app\models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "D:\projects\microblog\app\search.py", line 19, in query_index
    search = current_app.elasticsearch.search(
  File "d:\projects\microblog\myenv\lib\site-packages\elasticsearch\client\utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "d:\projects\microblog\myenv\lib\site-packages\elasticsearch\client\__init__.py", line 810, in search
    return self.transport.perform_request(
  File "d:\projects\microblog\myenv\lib\site-packages\elasticsearch\transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "d:\projects\microblog\myenv\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "d:\projects\microblog\myenv\lib\site-packages\elasticsearch\connection\base.py", line 181, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2019-12-01 00:10:54,561 ERROR: Exception on /search [GET] [in d:\projects\microblog\myenv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "d:\projects\microblog\myenv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\projects\microblog\myenv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\projects\microblog\myenv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\projects\microblog\myenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\projects\microblog\myenv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\projects\microblog\myenv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\projects\microblog\myenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\projects\microblog\app\main\routes.py", line 141, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "D:\projects\microblog\app\models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "D:\projects\microblog\app\search.py", line 19, in query_index
    search = current_app.elasticsearch.search(
  File "d:\projects\microblog\myenv\lib\site-packages\elasticsearch\client\utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "d:\projects\microblog\myenv\lib\site-packages\elasticsearch\client\__init__.py", line 810, in search
    return self.transport.perform_request(
  File "d:\projects\microblog\myenv\lib\site-packages\elasticsearch\transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "d:\projects\microblog\myenv\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "d:\projects\microblog\myenv\lib\site-packages\elasticsearch\connection\base.py", line 181, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
